management:
  endpoints:
    web:
      exposure:
        include: "health, info, mappings, metrics, loggers, shutdown, pause, resume"

server:
  port: 8081

spring:
  application:
    name: user
  profiles:
    active: development
  data:
    mongodb:
      database: aatruckdetailDB
      uri: mongodb+srv://aatruckdetail:i9XYt1q2xIIxvmaE@aatruckcluster.mysmi.mongodb.net/?retryWrites=true&w=majority